### ISSUE TITLE
global组件无法正确加载空间动态

### ISSUE THREAD

**Issue by Aintor** [BiliUniverse/Universe#106]
使用shadowrocket 2.2.37，global采用http模式。进入up主空间时特别缓慢，无法加载up主动态（但可以加载视频和主页）。

**Comment by Aintor** [comment]
所以不能用的意思实际上是性能受到影响，而不是功能受影响？第一行直接写不能用但实际能用有点容易让人误解，或许改一下我就不会提交这种无用的issue了。

**Comment by VirgilClyne** [comment]
> 所以不能用的意思实际上是性能受到影响，而不是功能受影响？第一行直接写不能用但实际能用有点容易让人误解，或许改一下我就不会提交这种无用的issue了。

QX和小火箭无法MitM处理HTTP/2链接，这两个VPN app不具备此功能
