### ISSUE TITLE
APP从后台返回前台后 script失效

### ISSUE THREAD

**Issue by Amarterlus** [BiliUniverse/Universe#110]
如题 杀进程后重进enhanced和adblock能正常工作 但app进一次后台回来刷新就恢复了

**Comment by Amarterlus** [comment]
Stash 2.5.4 问题解决

**Comment by Amarterlus** [comment]
平台iOS Stash 2.5.4

**Comment by Amarterlus** [comment]
fixed in Stash 2.5.6

**Comment by eilse1** [comment]
QX 1.5.0-819同样有上述问题

**Comment by eilse1** [comment]
添加hostname=data.bilibili.com后解决，目前其他影响未知
