### ISSUE TITLE
能不能设置首页不推送竖屏视频？

### ISSUE THREAD

**Issue by yf31** [BiliUniverse/Universe#111]
如题， 大佬辛苦了

**Comment by ClydeTime** [comment]
没理解，我从未在首页刷到过竖屏视频，有没有相关截图。

**Comment by yf31** [comment]
> 没理解，我从未在首页刷到过竖屏视频，有没有相关截图。

有的，类似于我圈起来这种
![image](https://github.com/BiliUniverse/Universe/assets/74579592/1d36d05f-ce5e-4760-8736-10d844998ccd)
辛苦了

**Comment by ClydeTime** [comment]
![boxjs](https://github.com/BiliUniverse/Universe/assets/42362589/330b91d4-3130-4f86-91b9-aa5fdb933a84)
更新订阅，更新BoxJS，重新设置。

**Comment by yf31** [comment]
太强了👍
