### ISSUE TITLE
ADBlock插件无法屏蔽7.69.0+版本的部分推荐广告

### ISSUE THREAD

**Issue by samduanx** [BiliUniverse/Universe#141]
如题，Beta版同样存在。
不能屏蔽的有：首页横幅、推荐流中装扮和大会员广告。

**Comment by ClydeTime** [comment]
首页横幅就是boxjs设置中的去除“活动大图”，测试功能正常。至于其他的广告只能见一个消灭一个，最好能提供下抓包，非常感谢！

**Comment by samduanx** [comment]
又使用粉色版本v7.72.0进行了测试，发现活动大图**只在推荐单列模式下才会出现**，双列模式没有。

**Comment by ClydeTime** [comment]
> 又使用粉色版本v7.72.0进行了测试，发现活动大图**只在推荐单列模式下才会出现**，双列模式没有。

做了很多次测试，均未发现上述问题，怀疑模块是否正常开启，请提供脚本的日志，而非代理工具的日志。

**Comment by samduanx** [comment]
暂未发现Loon有较好的插件调试手段，因此可关闭此issue。
