### ISSUE TITLE
BiliGlobal出现导致部分视频跳转加载成其他视频的bug

### ISSUE THREAD

**Issue by Ligneous** [BiliUniverse/Universe#164]
Bilibili Global会导致部分视频点进去后自动跳到另一个视频，同时伴随着评论区也是跳转后视频的评论区，而视频简介区域up主那一块仍然是原视频。同时历史记录里只能看到跳转后视频的历史记录。

出现该问题的那些视频可以反复稳定触发，关闭Bilibili Global则无此问题。
疑似和tg群组内其他人此前遇到的自己投稿的视频点开变成别人的视频是同一问题。

举例：BV1g6YLeqEit点进去视频和评论区实际是BV1dx4y137Fe
![IMG_1454](https://github.com/user-attachments/assets/eec0fbaa-c4c6-4c02-96b8-6409e3d721f6)

**Comment by carrotluo5** [comment]
+1，最开始我还以为是重定向问题

**Comment by yangzixmt** [comment]
遇到同样的问题

**Comment by SoaringYao** [comment]
遇到同样的问题

**Comment by SoaringYao** [comment]
遇到同样的问题
