### ISSUE TITLE
[ADBlock] 开启后，动态 - 综合部分刷新报错

### ISSUE THREAD

**Issue by Paladinfeng** [BiliUniverse/Universe#61]
- 错误日志：
![1B15C17E-86A4-46FA-B539-9FA8C7B856E0_1_102_o](https://github.com/BiliUniverse/Universe/assets/15520106/4c9dd53b-ee03-4849-82f7-5d586fa3ab5a)

**Comment by ClydeTime** [comment]
@Paladinfeng 测试版已更新，待🍟🍟更新到正式版后就没问题了
