### ISSUE TITLE
去广告功能能否适配iPad

### ISSUE THREAD

**Issue by Pollo3470** [BiliUniverse/Universe#68]
目前去广告功能无法过滤iPad bilibili和bilibili hd版上推荐页和详情页的广告

**Comment by ClydeTime** [comment]
请确保将脚本更到最新，如可能，将对应页截图提供下，谢谢

**Comment by Pollo3470** [comment]
不好意思最近比较忙忘记回复了，今天使用去广告插件后推荐页和视频页右侧的广告都已经可以正常过滤了，感谢作者大大！
