### ISSUE TITLE
Global模块无法播放限定大陆IP番剧

### ISSUE THREAD

**Issue by mingweiarthurli** [BiliUniverse/Universe#97]
Loon版本：3.1.0
Global版本：[c149f91](https://github.com/BiliUniverse/Global/commit/c149f919c971c7ba2b2d3376b01106980f69a6c3)
BoxJS设置：
- 强制CDN主机名类型：HTTP
- 自动识别地区：中国大陆、中国香港、中国台湾
问题番剧：https://www.bilibili.com/bangumi/play/ss43164

症状：
如果在BoxJS中同时启用中国大陆及中国香港或中国台湾之一，则播放限定大陆IP番剧时会提示“所在地区无法观看本片”，如果只开启中国大陆则没有此问题。
通过将BoxJS中的策略组修改为不存在的策略组名，当大陆和香港同时开启时，Loon会提示香港策略组不存在，说明调用的是香港策略组。如果同时开启大陆和台湾则会提示台湾策略组不存在。如果同时开启大陆、香港和台湾，也还是提示台湾策略组不存在。（我没有测试澳门，但很可能也有这个问题）。
由于我在加拿大，希望用Global模块达到自动切换IP看番的目的，有将识别为中国大陆番剧时调用的策略组从DIRECT改为对应策略组，不确定如果真实IP是国内的话是否也能复现该问题。
我没有Stash，所以也无法确定Stash上是否也有此问题。

**Comment by VirgilClyne** [comment]
已知问题，Bilibili 于近期更换了番剧信息的api，需要重新适配
